version: '{branch}-0.0.{build}'
skip_tags: true
image: Visual Studio 2017
branches:
  only:
    - master

environment:
  matrix:
  - QT: 5.11.1  
    build: 64
    qt_target: msvc2017_64
#  - qt: 5.11.1
#    build: 64
#    qt_target: winrt_armv7_msvc2017
  - qt: 5.11.1
    build: 32
    qt_target: winrt_x86_msvc2017
  - qt: 5.11.1
    build: 64
    qt_target: winrt_x64_msvc2017
           

install:
  - set QTDIR=C:\Qt\%qt%\%qt_target%
  - set PATH=%PATH%;%QTDIR%\bin
  - '%QTDIR%\bin\qtenv2.bat'
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%build%.bat"
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=C:\\Qt\\5.11.1\\%qt_target%\\lib\\cmake\\Qt5 -G "CodeBlocks - NMake Makefiles" %APPVEYOR_BUILD_FOLDER%
build_script:
  - cmake --build %APPVEYOR_BUILD_FOLDER%\\build --target SMART
  - cd ..
  - windeployqt %APPVEYOR_BUILD_FOLDER%/build/SMART.exe

after_build:
  - 7z a smart-%qt%-%qt_target%-%appveyor_build_version%.zip 
    %APPVEYOR_BUILD_FOLDER%\build\
    -xr!*.cpp
    -xr!*.obj
    -xr!*.h
    -xr!*.Cache
    -xr!*.intermediate    


artifacts:
  - path: '*.zip'
    name: smart %APPVEYOR_REPO_BRANCH% %qt% %qt_target% %appveyor_build_version% binary

deploy:
- provider: GitHub
  auth_token:
    secure: cfQYapw1kaToQWhkDuAZI7Q6VUBCDmRqm/+eziQ8yJoekJXgT3l8JBAflzCtpLVe
  repository: GaitRehabilitation/SMART
  artifact: /.*\.zip/
