version: '{branch}-0.0.{build}'
skip_tags: true
image: Visual Studio 2017
branches:
  only:
    - master

environment:
  matrix:
  - QT: 5.11.1  
    build: 64
    qt_target: msvc2017_64
	cmake_command_args: "Visual Studio 14 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:\\Qt\\5.11.1\\msvc2017_64\\lib\\cmake
#  - qt: 5.11.1
#    build: 64
#    qt_target: winrt_armv7_msvc2017
  - qt: 5.11.1
    build: 32
    qt_target: winrt_x86_msvc2017
  - qt: 5.11.1
    build: 64
    qt_target: winrt_x64_msvc2017
           

install:
  - set QTDIR=C:\Qt\%qt%\%qt_target%
  - set PATH=%PATH%;%QTDIR%\bin
  
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%build%.bat"
  - git submodule update --init --recursive
  - cmake -G %cmake_command_args%
  
build:
  - project: INSTALL.vcxproj 

after_build:
  - 7z a smart-%qt%-%qt_target%-%appveyor_build_version%.zip 
    %APPVEYOR_BUILD_FOLDER%\release\
    -xr!*.cpp
    -xr!*.obj
    -xr!*.h
    -xr!*.Cache
    -xr!*.intermediate    


artifacts:
  - path: '*.zip'
    name: smart %APPVEYOR_REPO_BRANCH% %qt% %qt_target% %appveyor_build_version% binary

deploy:
- provider: GitHub
  auth_token:
    secure: cfQYapw1kaToQWhkDuAZI7Q6VUBCDmRqm/+eziQ8yJoekJXgT3l8JBAflzCtpLVe
  repository: GaitRehabilitation/SMART
  artifact: /.*\.zip/
