version: '{branch}-0.0.{build}'
skip_tags: true
image: Visual Studio 2017

environment:
  matrix:
  - qt: 5.11.2  
    build: 64
    qt_target: msvc2017_64
#  - qt: 5.11.1
#    build: 64
#    qt_target: winrt_armv7_msvc2017
  - qt: 5.11.2
    build: 32
    qt_target: winrt_x86_msvc2017
  - qt: 5.11.2
    build: 64
    qt_target: winrt_x64_msvc2017
           

install:
  - set QTDIR=C:\Qt\%qt%\%qt_target%
  - set PATH=%PATH%;%QTDIR%\bin
before_build:
  - git config --global user.email "polli104@mail.chapman.edu"
  - git config --global user.name "Michael Pollind"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%build%.bat"
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=C:\\Qt\\%qt%\\%qt_target%\\lib\\cmake -DCPACK_PACKAGE_VERSION=%appveyor_build_version%  -G "CodeBlocks - NMake Makefiles" %APPVEYOR_BUILD_FOLDER%
build_script:
  - cmake --build %APPVEYOR_BUILD_FOLDER%\\build --target SMART
  - cd %APPVEYOR_BUILD_FOLDER%\\build
  - cpack -G ZIP --verbose
  - cpack -G NSIS --verbose

artifacts:
  - path: '**\*\_CPack_Packages\**\*.zip'
    name: smart %APPVEYOR_REPO_BRANCH% %qt% %qt_target% %appveyor_build_version% binary
  - path: '**\*\_CPack_Packages\**\*.exe'
    name: smart %APPVEYOR_REPO_BRANCH% %qt% %qt_target% %appveyor_build_version% installer

on_failure:
- appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\\build\\_CPack_Packages\\win64\\NSIS\\PreinstallOutput.log

deploy:
- provider: GitHub
  auth_token:
    secure: cfQYapw1kaToQWhkDuAZI7Q6VUBCDmRqm/+eziQ8yJoekJXgT3l8JBAflzCtpLVe
  repository: GaitRehabilitation/SMART
