image: Visual Studio 2017
branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.11.1\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin
  
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - git submodule init
  - git submodule update

build_script:
  - qmake -tp vc
  - msbuild /p:Configuration=Release
  - windeployqt ./release/SensorCapture.exe

after_build:
  - 7z a app.zip >
    %APPVEYOR_BUILD_FOLDER%\release\_pkginfo.txt 
    %APPVEYOR_BUILD_FOLDER%\release\iconengines 
    %APPVEYOR_BUILD_FOLDER%\release\imageformats 
    %APPVEYOR_BUILD_FOLDER%\release\microsoft.system.package.metadata 
    %APPVEYOR_BUILD_FOLDER%\release\platforms\  
    %APPVEYOR_BUILD_FOLDER%\release\SensorCapture.tlog\  
    %APPVEYOR_BUILD_FOLDER%\release\translations\  
    %APPVEYOR_BUILD_FOLDER%\release\*.dll  
    %APPVEYOR_BUILD_FOLDER%\release\*.xml
    %APPVEYOR_BUILD_FOLDER%\release\*.resfiles
    %APPVEYOR_BUILD_FOLDER%\release\*.txt
    %APPVEYOR_BUILD_FOLDER%\release\*.log
    %APPVEYOR_BUILD_FOLDER%\release\*.exe
    %APPVEYOR_BUILD_FOLDER%\release\*.build.appxrecipe

artifacts:
  - path: app.zip
    name: App
