version: '{build}-{branch}'

image: Visual Studio 2017
branches:
  only:
    - master

environment:
  matrix:
  - QT: 5.11.1  
    build: 64
    qt_target: msvc2017_64
#  - qt: 5.11.1
#    build: 64
#    qt_target: winrt_armv7_msvc2017
  - qt: 5.11.1
    build: 32
    qt_target: winrt_x86_msvc2017
  - qt: 5.11.1
    build: 64
    qt_target: winrt_x64_msvc2017
           

install:
  - set QTDIR=C:\Qt\%qt%\%qt_target%
  - set PATH=%PATH%;%QTDIR%\bin
  
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%build%.bat"
  - git submodule update --init --recursive

build_script:
  - qmake -tp vc
  - msbuild /p:Configuration=Release /p:AppxPackageSigningEnabled=false
  - windeployqt ./release/SensorCapture.exe

after_build:
  - 7z a smart_%appveyor_build_version%.zip 
    %APPVEYOR_BUILD_FOLDER%\release\
    -xr!*.cpp
    -xr!*.obj
    -xr!*.h
    -xr!*.Cache
    -xr!*.intermediate    


artifacts:
  - path: '*.zip'
    name: smart %APPVEYOR_REPO_BRANCH% %qt% %qt_target% %appveyor_build_version% binary
