version: '{build}-{branch}'

image: Visual Studio 2017
branches:
  only:
    - master

environment:
  matrix:
  - QT: 5.11.1
    build: 64
    platform: msvc2017_64
  - qt: 5.11.1
    build: 64
    platform: winrt_armv7_msvc2017
  - qt: 5.11.1
    build: 32
    platform: winrt_x86_msvc2017
  - qt: 5.11.1
    build: 64
    platform: winrt_x64_msvc2017
           

install:
  - set QTDIR=C:\Qt\%qt%\%platform%
  - set PATH=%PATH%;%QTDIR%\bin
  
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%build%.bat"
  - git submodule init
  - git submodule update

build_script:
  - qmake -tp vc
  - msbuild /p:Configuration=Release /p:AppxPackageSigningEnabled=false
  - windeployqt ./release/SensorCapture.exe

after_build:
  - 7z a sensor_capture_%platform%_%qt%_%version%.zip 
    %APPVEYOR_BUILD_FOLDER%\release\
    -xr!*.cpp
    -xr!*.obj
    -xr!*.h
    -xr!*.Cache
    -xr!*.intermediate    


artifacts:
  - path: '*.zip'
    name: App
